#!/usr/bin/env bash
# Run the cytoid_game_core pure-logic Swift test suite without the
# FlutterFramework SPM package or the UnityFramework binary target.
#
# This realizes the "isolated SwiftPM sandbox" convention referenced in
# Sources/cytoid_game_core/*.swift comments. The harness:
#   1. Symlinks production Sources/ files into a sandbox package, excluding
#      CytoidGameCorePlugin.swift (the Flutter entry point — uses FlutterPlugin,
#      FlutterMethodChannel, FlutterPluginRegistrar, which we do not stub).
#   2. Symlinks 7 of 8 test files, excluding ShowGameSurfaceAtomicityTests.swift
#      (asserts on real FlutterError wrapping semantics).
#   3. Generates a tiny in-tree Flutter stub module providing the four types
#      the non-excluded sources reference: FlutterResult, FlutterEventSink,
#      FlutterError, FlutterStreamHandler.
#   4. Generates a stripped Package.swift with no FlutterFramework package
#      dependency, no UnityFramework binary target, no
#      CYTOID_UNITY_FRAMEWORK_AVAILABLE define.
#   5. Runs `swift test` on the macOS host; forwards the exit code.
#
# Why symlink not copy: production source changes are picked up on the next
# run without a sync step. The sandbox is a build cache, not a fork.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLUGIN_IOS_DIR="$ROOT_DIR/ios/cytoid_game_core"
SANDBOX_DIR="$ROOT_DIR/.cytoid_game_core/swift-test-sandbox"

# Production source files excluded from sandbox (require real Flutter / UIKit).
EXCLUDED_SOURCE_FILES=("CytoidGameCorePlugin.swift")
# Test files excluded from sandbox (assert on real Flutter semantics).
EXCLUDED_TEST_FILES=("ShowGameSurfaceAtomicityTests.swift")

usage() {
  cat <<EOF
Usage: $(basename "$0") [--clean] [--list-tests] [--help]

Runs the cytoid_game_core pure-logic Swift test suite in an isolated SwiftPM
sandbox. No FlutterFramework SPM package or UnityFramework binary target
needed; a tiny Flutter API stub is generated so files that \`import Flutter\`
compile. Tests requiring real Flutter semantics are excluded.

Options:
  --clean        Wipe the sandbox before regenerating.
  --list-tests   Run \`swift test --list-tests\` instead of executing them.
  --help, -h     Show this help and exit.
EOF
}

CLEAN=0
LIST_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --clean)    CLEAN=1 ;;
    --list-tests) LIST_ONLY=1 ;;
    --help|-h)  usage; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; usage >&2; exit 64 ;;
  esac
done

if [[ ! -d "$PLUGIN_IOS_DIR/Sources/cytoid_game_core" ]]; then
  echo "Production Sources/cytoid_game_core not found at $PLUGIN_IOS_DIR" >&2
  exit 1
fi

if [[ "$CLEAN" == "1" ]]; then
  rm -rf "$SANDBOX_DIR"
fi

mkdir -p "$SANDBOX_DIR"

# -----------------------------------------------------------------------------
# 1. Symlink selected production source files.
# -----------------------------------------------------------------------------
mkdir -p "$SANDBOX_DIR/Sources/cytoid_game_core"
for src in "$PLUGIN_IOS_DIR/Sources/cytoid_game_core"/*.swift; do
  name="$(basename "$src")"
  skip=0
  for excluded in "${EXCLUDED_SOURCE_FILES[@]}"; do
    [[ "$name" == "$excluded" ]] && skip=1 && break
  done
  [[ "$skip" == "1" ]] && continue
  ln -sfn "$src" "$SANDBOX_DIR/Sources/cytoid_game_core/$name"
done

# -----------------------------------------------------------------------------
# 2. Symlink selected test files.
# -----------------------------------------------------------------------------
mkdir -p "$SANDBOX_DIR/Tests/cytoid_game_coreTests"
for test in "$PLUGIN_IOS_DIR/Tests/cytoid_game_coreTests"/*.swift; do
  name="$(basename "$test")"
  skip=0
  for excluded in "${EXCLUDED_TEST_FILES[@]}"; do
    [[ "$name" == "$excluded" ]] && skip=1 && break
  done
  [[ "$skip" == "1" ]] && continue
  ln -sfn "$test" "$SANDBOX_DIR/Tests/cytoid_game_coreTests/$name"
done

# -----------------------------------------------------------------------------
# 3. Generate the stub Flutter module.
# -----------------------------------------------------------------------------
mkdir -p "$SANDBOX_DIR/Sources/Flutter"
cat >"$SANDBOX_DIR/Sources/Flutter/Flutter.swift" <<'STUB_EOF'
// GENERATED BY run_swift_tests_sandboxed.sh — DO NOT EDIT IN PRODUCTION.
// Minimal Flutter iOS SDK API surface stub. NOT for production use.
// Provides only the four symbols referenced by the sandbox-eligible
// production sources:
//   - FlutterResult, FlutterEventSink (typealiases)
//   - FlutterError (class)
//   - FlutterStreamHandler (protocol)
// Any production source that grows to need additional Flutter API surface
// MUST be either (a) added to EXCLUDED_SOURCE_FILES in the harness, or
// (b) have the new symbol added to this stub. The harness will fail to
// compile to make the gap visible.
import Foundation

public typealias FlutterResult = (Any?) -> Void
public typealias FlutterEventSink = (Any?) -> Void

public final class FlutterError: Error, CustomDebugStringConvertible {
    public let code: String
    public let message: String?
    public let details: Any?

    public init(code: String, message: String?, details: Any?) {
        self.code = code
        self.message = message
        self.details = details
    }

    public var debugDescription: String {
        "FlutterError(code: \(code), message: \(message ?? "nil"))"
    }
}

public protocol FlutterStreamHandler {
    func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError?
    func onCancel(withArguments arguments: Any?) -> FlutterError?
}
STUB_EOF

# -----------------------------------------------------------------------------
# 4. Generate the stripped Package.swift.
# -----------------------------------------------------------------------------
cat >"$SANDBOX_DIR/Package.swift" <<'PKG_EOF'
// swift-tools-version: 5.9
// GENERATED BY run_swift_tests_sandboxed.sh — DO NOT EDIT.
// Isolated SwiftPM sandbox package. No FlutterFramework package dependency,
// no UnityFramework binary target, no CYTOID_UNITY_FRAMEWORK_AVAILABLE define.
// Target/module names match production so symlinks + @testable import work
// without rewriting.
import PackageDescription

let package = Package(
    name: "cytoid_game_core_sandbox",
    platforms: [
        // Tests run on the macOS host; production code in the symlinked
        // sources uses only Foundation + the stub Flutter module, no UIKit.
        .macOS("12.0")
    ],
    products: [
        .library(name: "cytoid_game_core", targets: ["cytoid_game_core"])
    ],
    targets: [
        .target(
            name: "Flutter",
            path: "Sources/Flutter"
        ),
        .target(
            name: "cytoid_game_core",
            dependencies: ["Flutter"],
            path: "Sources/cytoid_game_core"
        ),
        .testTarget(
            name: "cytoid_game_coreTests",
            dependencies: ["cytoid_game_core"],
            path: "Tests/cytoid_game_coreTests"
        )
    ]
)
PKG_EOF

# -----------------------------------------------------------------------------
# 5. Run swift test (or --list-tests).
# -----------------------------------------------------------------------------
cd "$SANDBOX_DIR"
if [[ "$LIST_ONLY" == "1" ]]; then
  swift test --list-tests
else
  echo "[run_swift_tests_sandboxed] sandbox at $SANDBOX_DIR"
  swift test
fi
